version: '3.8'

services:
  frontend:
    container_name: wishwithme-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - wishwithme

networks:
  wishwithme:
    external: true
